services:
  service-db:
    image: postgres:11.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432
    volumes:
      - ./infrastructure/db:/docker-entrypoint-initdb.d
    restart: unless-stopped
  service-airline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airline-container
    depends_on:
      - service-db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://service-db/airline
      SPRING_PROFILES_ACTIVE: dev